remove unnecessary imports
pz-max/pypsa-africa pull request #1020
Opened 2024-05-02 11:05 UTC by finozzifa

# Closes # (if applicable).

## Changes proposed in this Pull Request

## Checklist

- [x ] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2024-05-02 20:00 UTC, davide-f requested changes
Thanks @finozzifa :D
That's a very nice PR and soon ready to merge.

As additional element, the "import logging" should in theory be dropped everywhere except the helpers.
To me it seems that remains in build_powerplants for an old missing dependencies (see comment into the file) and also into build_cutout because we have an old "logging.info/warning" that should be revised into "logger.info/warning"
Could you check that?
After that, the PR can be merged :D

2024-05-02 20:00 UTC, davide-f commented on scripts/retrieve_databundle_light.py
> +.. see also::
This is a keyword, can you revert?

2024-05-02 20:00 UTC, davide-f commented on scripts/build_powerplants.py
> -from build_shapes import get_GADM_layer
In this script, the import logging should be dropped as well.
there are two lines (368 and 372) that still do logging.warning, but they should be revised into "logger.warning". Could you revise that and drop logging dependency?

2024-05-03 07:46 UTC, finozzifa commented on scripts/retrieve_databundle_light.py
> +.. see also::
Hi Davide. Thanks :)

2024-05-03 07:46 UTC, finozzifa commented on scripts/build_powerplants.py
> -from build_shapes import get_GADM_layer
done!

2024-05-03 13:31 UTC, davide-f approved these changes
Great @finozzifa :D
This PR is ready to go :)

2024-05-03 13:31 UTC, merged