Finalize duplication of retrieve_data
pz-max/pypsa-africa pull request #1249
Opened 2024-12-21 12:40 UTC by davide-f

# Closes # (if applicable).

## Changes proposed in this Pull Request
This PR builds on top of #1120 to avoid duplication of retrieve_data function, bump technology data version and drop cost_dir option.

Note: dropping cost_dir is in line with pypsa-eur and we also had a TODO on that, but before merging this PR, there is the need for a check by @hazemakhalek , @Eddy-JV or @energyLS given its use in the -sec model.
Moreover, bumping the latest version of the default technology data to the latest will change values of the CI

## Checklist

- [x] I consent to the release of this PR's code under the AGPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `doc/requirements.txt`.
- [x] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [x] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2024-12-21 17:08 UTC, ekatef requested changes
Hello @davide-f, looks like a very nice improvement!

My major concern is that the PR also contains some improvements which relate to improvements for alternative clustering. It feels like there may be some connections with other issues and fixes, but the context is not quite clear from the PR. Given the fact that alternative clustering seems to be one of the major points to be tackled, I'd suggest to keep in this PR only cost-related improvements and open another dedicated PR for the improvements on alternative clustering. What do you think?

The costs-related part looks great and basically ready to merge, unless there are some comments from @hazemakhalek @Eddy-JV and @energyLS

2024-12-21 17:08 UTC, ekatef commented on scripts/build_renewable_profiles.py
> +
Looks like a very interesting improvement which potentially could resolve some current issues with alternative clustering. However, if looks like this part introduces changes into structure of bus regions which must be generated by `build_shapes`. So, it feels more natural to move this fragment there

2024-12-21 17:08 UTC, ekatef commented on scripts/build_renewable_profiles.py
> +        ### TODO: quickfix. above case and the below case should by unified
Would it be possible to replace this TODO by introducing this unification? 

Also, that is not quite clear which particular issue is targeted by these changes. Would be great to clarify that as both the alternative clustering and the hydro part actually require some improvements, so it would be great to track the status there 🙂

2024-12-21 17:08 UTC, ekatef commented on scripts/build_renewable_profiles.py
> +        if snakemake.params.alternative_clustering == False:
The comment sounds as the improvements were a part of some other improvements chain. Would be great to give some more context to make sure that all the work streams are aligned

2024-12-21 18:04 UTC, davide-f commented on scripts/build_renewable_profiles.py
> +
Done, that proposal links to another issue related to multiple hydro units in the same bus

2024-12-21 18:04 UTC, davide-f commented on scripts/build_renewable_profiles.py
> +        ### TODO: quickfix. above case and the below case should by unified
Done, that proposal links to another issue related to multiple hydro units in the same bus

2024-12-21 18:04 UTC, davide-f commented on scripts/build_renewable_profiles.py
> +        if snakemake.params.alternative_clustering == False:
Done, that proposal links to another issue related to multiple hydro units in the same bus

2024-12-21 18:20 UTC, ekatef approved these changes

2024-12-21 18:25 UTC, ekatef commented
@davide-f thanks a lot for introducing the changes! Totally agree that tackling the hydro improvements deserves a dedicated issue. Thanks for taking care about that 🙂 

I think this PR is ready to merge if there is no objections from the experts on the sector-coupled part 🚀 Great work! 😄

2025-01-09 09:24 UTC, energyLS commented
@energyLS doublecheck

2025-01-09 09:31 UTC, davide-f commented
Update. @ekatef given the recent alternative_clustering issue and the possible fix https://github.com/pypsa-meets-earth/pypsa-earth/pull/1287
it could be advisable to restore the proposal on alternative clustering in #1120 . Recent tests have identified that ror technology can be lost in #1287

2025-01-09 23:23 UTC, ekatef reviewed
Looks very good! 😄 

I remember that the PR combines changes related both to file management for costs and improvements for hydro calculations. To help disentangle it, may it be a good idea to add a duplicated release note on hydro along with the existing one?

2025-01-09 23:23 UTC, ekatef commented on doc/release_notes.rst
May it be a good idea to add another release note mentioning the same PR to document also the changes in processing hydro profiles?

2025-01-09 23:27 UTC, ekatef commented
Have checked the objective, and it appears that the only significant change of ~8% relates to the second test case (the one with `config.custom.yaml` with alternative clustering on): `2157472538.0` in this PR vs `2341159535.0`. Interestingly, that the objective remains exactly the same for myopic test case though it's also using alternative clustering.

Also, there is ~4% change for one of the Monte-Carlo tests (the one with very low objective function), but I remember that we had it previously (looking on [this comment](https://github.com/pypsa-meets-earth/pypsa-earth/pull/1172#issuecomment-2569882202)) and it's normal, right?

2025-01-10 15:42 UTC, davide-f commented on doc/release_notes.rst
Updated :)

2025-01-10 18:24 UTC, ekatef approved these changes

2025-01-10 19:12 UTC, merged