Gadm clustering
pz-max/pypsa-africa pull request #264
Opened 2022-02-11 14:03 UTC by Hazem-IEG

# Closes #141 .

## Changes proposed in this Pull Request
The buses are only mapped to the shapes of their countries

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes.

2022-03-18 11:33 UTC, davide-f commented
Finally, check the checklist of the PR template; in particular, a change in release_notes, like "bug fixing of overlapping/clustering shapes" may be helpful; obviously change it as you please.

2022-03-26 22:12 UTC, davide-f requested changes
I added some comments in the text without the review

2022-03-26 22:12 UTC, davide-f commented on scripts/build_bus_regions.py
> +            gadm_shapes_country = gadm_shapes.filter(like='TUN', axis=0)        #TODO change the naming to 2 letter
This conversion can be done using the helper function
https://github.com/pypsa-meets-africa/pypsa-africa/blob/c994217e2c5fff891e39dde5fe6da6d27757c498/scripts/_helpers.py#L396

Same logic applies later (function get_id), I don't repeat the comment.

Though, why this if is needed?

2022-03-26 22:12 UTC, davide-f commented on scripts/build_bus_regions.py
> +            return min(gadm_shapes_country, key=(point.distance))             # TODO
May you elaborate the TODO slightly?

2022-03-26 22:12 UTC, davide-f commented on scripts/cluster_network.py
> +    #n.buses.at[['3773'], 'country']='BJ'
May these be removed?

2022-03-26 22:12 UTC, davide-f commented on scripts/build_bus_regions.py
>          try:
May you add a comment about this try to ease the use by a third developer.
It seems to me that if the shape cannot be identified univocally, the closest shape is selected, right?

2022-03-29 18:49 UTC, pz-max commented
Need to replace centroid by polylabel to set the bus in the visual center - correctly.  See issue: https://github.com/pypsa-meets-africa/pypsa-africa/issues/191

2022-04-20 14:07 UTC, Hazem-IEG commented
I adapted the code to the comments and it works well except with hydro enabled in the config file. When enabled, add_electricity crashes with an assertion error. If this is a known error that happens in the main branch anyway then the PR should be ready to merge. @davide-f

2022-04-21 11:06 UTC, davide-f commented
What is the hydro issue you are referring to?
Unfortunately, I am not aware of it

2022-05-16 14:17 UTC, davide-f commented
@Hazem-IEG to fix this, I guess it would be easy to use the validation_nigeria file that is in main right now, I guess you may have used it for debugging.

A question: in this PR there are some binary files, are they supposed to be here?
I fear we may add MBs to our git history that is already very large

2022-05-23 12:30 UTC, davide-f commented
@Hazem-IEG Are you using the environment while doing the analysis?
The pre-commit is not passing

2022-05-23 14:11 UTC, davide-f commented
@Hazem-IEG I think I've fixed the issue, later we can merge it :)

2022-05-23 15:11 UTC, davide-f approved these changes

2022-05-23 15:12 UTC, merged