world_iso list modified
pz-max/pypsa-africa pull request #330
Opened 2022-04-28 12:01 UTC by HanaElattar

# Closes # (if applicable).

## Changes proposed in this Pull Request

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`, `config.tutorial.yaml`, and `test/config.test1.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2022-04-29 00:05 UTC, davide-f requested changes
Thank you for the contributions! Very detailed work :)
I added few simple comments.

Moreover, the pre-commit is not working.
To successfully use it, I recommend you to do as in https://pypsa-meets-africa.readthedocs.io/en/latest/installation.html , in particular:
- Use an IDE to edit python (recommended Visual Studio Code that is open)
- Install the pypsa-africa environment (see guide)
- Always make edits and commits after having enabled the environment [In VSCode, this may be easily done automatically by setting View->Command Pallette->Python Interpreter->pypsa-africa)

2022-04-29 00:05 UTC, davide-f commented on scripts/config_osm_data.py
> +       	// # canary-islands    # Island
Unnecessary "//"; this throws an error in the CI, which is a workflow that is run to check if the contributions are safe to merge

2022-04-29 00:05 UTC, davide-f commented on scripts/config_osm_data.py
> +	    "TF": "french-southern-territories",
Harmonize the data, there is here an unnecessary tab; this issue happens also below

2022-04-29 00:05 UTC, davide-f commented on scripts/config_osm_data.py
> +       "DZ": "algeria",
Modify as it was before

2022-05-03 13:21 UTC, davide-f commented
@HanaElattar , if you need any help on the above, feel free to write on Discord or here :)

2022-05-27 10:30 UTC, HanaElattar commented
Added a list of countries but couldn't test that the workflow runs. Could be for future work.

2022-05-27 10:30 UTC, merged