landlock countries fix
pz-max/pypsa-africa pull request #465
Opened 2022-10-01 11:42 UTC by DeniseGiub

## Changes proposed in this Pull Request

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [x] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2022-10-01 20:07 UTC, pz-max requested changes
Changes look good. However, the code would break if the config.yaml clusters GADM shapes. To do: 
- [x] create a test for alternative_clustering: True
- [ ] Make the whole workflow working with alternative_clusterin: True (undo a couple of changes)

2022-10-01 20:07 UTC, pz-max commented on scripts/build_bus_regions.py
> -            onshore_geometry = get_gadm_shape(onshore_locs, gadm_shapes)[0]
This deletes the GADM clustering functionalities (see our preprint)
We could create a test for checking `["alternative_clustering"]: True` to detect such breaking changes in future.

2022-10-02 20:03 UTC, davide-f commented
> Changes look good. However, the code would break if the config.yaml clusters GADM shapes. To do:
> 
> * [ ]  create a test for alternative_clustering: True
> * [ ]  Make the whole workflow working with alternative_clusterin: True (undo a couple of changes)

@DeniseGiub Great Job!

@pz-max for flexibility purposes, rather than creating a new file, which may lead to duplication, we could do some hacking to create it dynamically with the CI.
The other test config would be copy and paste of the other one, with few parameters changed; if we change the config file then we have to change 2 files instead of one.

2022-10-10 18:05 UTC, pz-max commented
> @pz-max for flexibility purposes, rather than creating a new file, which may lead to duplication, we could do some hacking to create it dynamically with the CI. The other test config would be copy and paste of the other one, with few parameters changed; if we change the config file then we have to change 2 files instead of one.

We redesigned the testing procedure in this PR: https://github.com/pypsa-meets-earth/pypsa-earth/pull/466
It will be merged after a successful CI run.

2022-10-14 10:22 UTC, closed without merging