Add run scenarios
pz-max/pypsa-africa pull request #543
Opened 2022-12-25 16:57 UTC by davide-f

# Closes # (if applicable).

## Changes proposed in this Pull Request
This branch aims at creating rules and scripts to iteratively test the workflow on a list of countries.
For each country, the workflow is executed and general statistics are collected.
Intermediate results are also stored.
This can be useful to track the overall status of the workflow for the globe, also collecting statistics that can be useful for validation.

Suggestions are welcome, especially on the statistics to include.

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2022-12-25 17:35 UTC, ekatef commented
A technical suggestion: would it be possible to keep all the country names for which GADM_ID codes contain non-standard values, that is letters of `GADM_ID` do not correspond to the country code?

It would be very helpful to understand how often fine tuning may be needed when working with administrative data globally. And how much hard-coded could be a solution for non-standard cases :)

2022-12-25 18:44 UTC, davide-f commented
> A technical suggestion: would it be possible to keep all the country names for which GADM_ID codes contain non-standard values, that is letters of `GADM_ID` do not correspond to the country code?
> 
> It would be very helpful to understand how often fine tuning may be needed when working with administrative data globally. And how much hard-coded could be a solution for non-standard cases :)

Yeah :) that can be done absolutely, do you have some lines already developed to include that?
I'd just need a line that performs the check including fail-safe check if the datatype does not match.
I was wondering if you may like a test on the time series of renewables. Do you think it is needed?

2022-12-26 18:42 UTC, ekatef commented
> Yeah :) that can be done absolutely, do you have some lines already developed to include that?
> I'd just need a line that performs the check including fail-safe check if the datatype does not match.

Super :)
I'd suggest something like https://github.com/ekatef/pypsa-earth/blob/019a49bc95087d3f47fefd6fd8dc155f637cdd91/scripts/build_shapes.py#L145-L175

I have tried here to get use of pandas DataFrame `to_csv()` method with two approaches: 
* one utilising a pre-defined dataframe structure (and thus hopefully safer!),
*  another one writing a filtered-out chunk of the original dataframe (which would be more useful for analysis). 

Agree that we may need an additional safety check to ensure that the workflow will not be stopped due to some I/O errors. But don't have any particular ideas on this (except catching a non-specific exception...) and would be very interested in yours :)

2022-12-26 19:08 UTC, ekatef commented
> I was wondering if you may like a test on the time series of renewables. Do you think it is needed?

Absolutely! I'd be more than interested in any kind of validation procedures for renewables (and even a bit generally for climate factors). I see here two options:

1) we may try to compare the wind/solar potential calculated for (known) locations of the wind/PV generation against the known generation in these places;

2) we can extract climate variables for the locations of the meteorological stations to compare them against the observations and introduce the bias corrections.

Regarding the first point I'm afraid we are somewhat constrained with RES data availability for 2013.

As for the second approach, in my opinion it's a more "correct" way, and there data availability looks much better here. There are great global-scale meteorological datasets like [GHCN](https://www.sciencedirect.com/science/article/pii/S0098300418304230) or [ISD](https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database). I think it would be very useful to have an opportunity integrate them in our workflow but it may be not trivial at all :)

Probably, as an initial test we could just take a couple of dozens locations of meteorological stations (e.g. ones being representative for more or less global picture or just with the highest data quality) and extract wind/solar potential for the buses where these stations belong to?

What do you think?

2022-12-28 23:38 UTC, davide-f commented
So, I kind of implemented everything on the wish list, at least on a draft way:
- build_shapes: please, check the function `collect_shape_stats` for the statistics that are currently implemented
- build_renewable_profiles: please, check the function `collect_renewable_stats`

They are meant to be simple statistics to check the functionality of the workflow, yet they can be used for validation purposes and easy to expand to include additional features

I think this PR is ready for preliminary review and comparison.
Morever, we should discuss whether to include this to the codebase or not.

@pz-max and @ekatef , will you be available tomorrow for the workflow meeting?

2022-12-29 12:48 UTC, ekatef commented
Fantastic! Thank you so much :)
I think both `collect_shape_stats` and `collect_renewable_stats` look great and we'll be able to use their results very well. 

Will be happy to discuss details during the today's workflow meeting

2022-12-29 13:10 UTC, pz-max commented
Yes, let's talk today

2022-12-30 22:13 UTC, davide-f commented
A run :)
Some work is still needed.
Legend:
- green: network solved
- dark green: at least add_electricity worked, but network was not solved
- yellow: base_network was successful but add_electricity didn't
- orange: build_shapes worked but base_network not
- red: buils_shapes couldn't succeed

![statusmap](https://user-images.githubusercontent.com/67809479/210114715-51673739-85e1-4a7b-82da-30d51c50b0e2.png)

2022-12-30 22:41 UTC, pz-max commented
Nice map @davide-f . Is this figure created by the workflow? (We should regularly check the situation e.g. on weekly basis in near feature). It really shows that pypsa-earth is not yet stable to run everywhere.

2022-12-30 23:45 UTC, davide-f commented
> Nice map @davide-f . Is this figure created by the workflow? (We should regularly check the situation e.g. on weekly basis in near feature). It really shows that pypsa-earth is not yet stable to run everywhere.

I'm working on it and we can improve it; it was a nice mapping and testing.
A lot will be improved when https://github.com/PyPSA/powerplantmatching/pull/96 will be merged and included into conda.
Currently that is running again

2022-12-30 23:45 UTC, ekatef commented
A nice and very insightful plot!

Would it probably make sense to switch green and dark green to make the color coding more intuitive? (or probably replace gark green with something like gold or yellowgreen?..)

Results are a bit surprising: my a priori feeling was that the model works perfectly in 80% cases and tends to make troubles in really complicated cases only :) Is the yellow probably an effect of #531? And does red mean some regional borders uncertainties?

Agree that the visualisation works perfectly to highlight the modeling status and it's worth to include it into the regular workflow. Apart of this practical meaning, it's just beautiful :)

2022-12-30 23:49 UTC, davide-f commented
> A nice and very insightful plot!
> 
> Would it probably make sense to switch green and dark green to make the color coding more intuitive? (or probably replace gark green with something like gold or yellowgreen?..)
> 
> Results are a bit surprising: my a priori feeling was that the model works perfectly in 80% cases and tends to make troubles in really complicated cases only :) Is the yellow probably an effect of #531? And does red mean some regional borders uncertainties?
> 
> Agree that the visualisation works perfectly to highlight the modeling status and it's worth to include it into the regular workflow. Apart of this practical meaning, it's just beautiful :)

Green/dark green currently is not a problem, though I agree.
Before I was using blue.
The major issue now is that we need some little fixing and this mapping is actually something we really needed.
There was a problem with powerplantmatching that I'm investigating and proposed a fix.
The new map should be more realistic and close to the africa paper as well

2022-12-30 23:52 UTC, davide-f commented
> Nice map @davide-f . Is this figure created by the workflow? (We should regularly check the situation e.g. on weekly basis in near feature). It really shows that pypsa-earth is not yet stable to run everywhere.

I agree that we should update the figure especially after major bug-fixing

2023-01-02 17:20 UTC, davide-f commented
Image above updated

2023-01-02 17:48 UTC, ekatef commented
> Image above updated

Wow 🤩 An impressive progress!

2023-01-03 20:40 UTC, davide-f commented
Latest changes are updated above.
The image now looks pretty good. Some bug fixing has been needed in powerplantmatching/atlite and pypsa-earth.
That is the result.

For the purpose of this PR, no more bugfixing is expected, but I'll try run the same code on regions beyond africa.

Major changes to address are:
- adjust the clustering when DC buses are included. Probably, the best way would be to do the groupby by ["countries", "carrier"]; that would keep consistency in the carriers by bus without making explode the number of clusters; the effects of sub_networks shall be tested anyway.
- (second priority) Handling empty dataframes where necessary. The workflow failed in some countries because the clustering process occurring on buses without lines seemed to lead errors inside pypsa that may be addressed. An issue as been added in pypsa

2023-01-05 16:19 UTC, pz-max commented
Update. The picture is becoming more green :1st_place_medal: .. White areas still needs to be tested ![Screenshot from 2023-01-05 16-17-40](https://user-images.githubusercontent.com/61968949/210828529-2f3d0972-420b-40ac-8e96-3e9945f0ced6.png)

2023-01-08 15:54 UTC, davide-f commented
Latest updates.

I think this image cannot be released as of now: too much non-green in Asia.
Maybe the Africa+South America may be released (upper image)

Priorities to be fixed:
1. geometry shape whose draft fix is at https://github.com/pypsa-meets-earth/pypsa-earth/pull/532 . With the revised version and the option drop/set_to_country PK, IN and CH at least should become at least dark green
2. fix cluster network problem at https://github.com/pypsa-meets-earth/pypsa-earth/issues/531 . With this most of dark green areas should become clear.

After these fixes, I think the +Asia shape should be ok to be published.
In that case, we can also run Europe and North America

![img](https://user-images.githubusercontent.com/67809479/211206082-4bb5222b-3406-46bd-ace4-03e356e58cdf.png)

2023-01-24 09:21 UTC, davide-f commented
This PR will be heavily revised in agreement to the new developments on main.
A force push will update the code and a copy will be stored in my fork

2023-01-26 13:05 UTC, pz-max requested changes

2023-01-26 13:05 UTC, pz-max commented on scripts/build_test_configs.py
> +    fp_baseconfig = Path(Path.cwd(), base_path)
Docstring

2023-01-26 13:05 UTC, pz-max commented on Snakefile
> +        touch("results/{scenario_name}/scenario.done"),
Create a copy of the full config

2023-01-26 13:05 UTC, pz-max commented on Snakefile
> +        create_test_config(
Short # comment string would be helpful here

2023-01-26 13:05 UTC, pz-max commented on Snakefile
> +        base_config="config.default.yaml",
default config instead base_config?

2023-01-26 13:05 UTC, pz-max commented on Snakefile
> +        create_test_config(input.base_config, input.diff_config, "config.yaml")
same here, default_config?

2023-01-26 13:05 UTC, pz-max commented on Snakefile
> +                )
use pathlib instead: https://stackoverflow.com/questions/39909655/listing-of-all-files-in-directory (path.glob seems promising)

2023-01-26 13:26 UTC, davide-f commented on Snakefile
> +        create_test_config(input.base_config, input.diff_config, "config.yaml")
done

2023-01-26 13:26 UTC, davide-f commented on Snakefile
> +        create_test_config(
done

2023-01-26 13:26 UTC, davide-f commented on Snakefile
> +        touch("results/{scenario_name}/scenario.done"),
done

2023-01-26 13:26 UTC, davide-f commented on Snakefile
> +        base_config="config.default.yaml",
done

2023-01-26 13:26 UTC, davide-f commented on scripts/build_test_configs.py
> +    fp_baseconfig = Path(Path.cwd(), base_path)
Done

2023-01-26 13:26 UTC, davide-f commented on Snakefile
> +                )
Done

2023-01-26 13:40 UTC, pz-max approved these changes

2023-01-26 19:16 UTC, merged