Fix cleaning of OSM data
pz-max/pypsa-africa pull request #548
Opened 2022-12-28 23:16 UTC by ekatef

## Changes proposed in this Pull Request

Improves OSM data cleaning workflow

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2023-01-07 19:22 UTC, davide-f requested changes

2023-01-07 19:22 UTC, davide-f commented on scripts/clean_osm_data.py
> +    df_all_lines = split_cells(df_all_lines, lst_col="tag_frequency")
I think that the split_cells used here is improper as we duplicate line entries that may have the ";" in also the cables and circuits.
The tag_frequency should be added into the split_cells_multiple, but that function should be heavily improved to account for semicolumn partially missining in some columns.

In the case where semicolumn is found in tag_frequency, are the values consistent (e.i. "50;50") or not (e.i. ("50;0")?

2023-01-22 23:43 UTC, davide-f commented
@ekatef regarding this PR, in the case multiple entries are found for frequency may make sense to just consider the first value?
May you recall an example of values that needed this fix?
I'd be prone to do a simple fix and when the ";" is found to just get the first value of the list, provided that the elements are simple duplicated values.

2023-01-23 20:40 UTC, ekatef commented
@davide-f I have encountered multiple entries for frequency as `50;50`. So, taking the first entry should work fine

2023-01-24 13:06 UTC, davide-f commented
> @davide-f I have encountered multiple entries for frequency as `50;50`. So, taking the first entry should work fine

Thanks :)
Do you think you could propose a quick fix for this? forcepushing on this branch or opening a new PR may work fine

2023-01-24 21:34 UTC, ekatef commented
> > @davide-f I have encountered multiple entries for frequency as `50;50`. So, taking the first entry should work fine
> 
> Thanks :) Do you think you could propose a quick fix for this? forcepushing on this branch or opening a new PR may work fine

@davide-f, yes absolutely. Will be happy to add a fix for this. Although, not sure how quick is quick enough :) Do you see this issue as a blocking one?

2023-01-24 23:20 UTC, davide-f commented
> > > @davide-f I have encountered multiple entries for frequency as `50;50`. So, taking the first entry should work fine
> > 
> > 
> > Thanks :) Do you think you could propose a quick fix for this? forcepushing on this branch or opening a new PR may work fine
> 
> @davide-f, yes absolutely. Will be happy to add a fix for this. Although, not sure how quick is quick enough :) Do you see this issue as a blocking one?

I don't see it a blocking issue but since we have it and you already scouted it I think we could find a fix and then move to the AC/DC problem.
The fix I'd expect for this problem may be 1-2 lines basically. Something like:
``` python
df_all_lines["tag_frequency"] = df_all_lines["tag_frequency"].astype(str).str.split(pat=";",n=1)
```
Or something like that. The pat may be specified also with a regular expression to capture ; or , or alike but not sure if it makes sense to make it that complex

2023-01-29 16:17 UTC, closed without merging