REUSE compliance badge_v.0
pz-max/pypsa-africa pull request #617
Opened 2023-03-05 18:54 UTC by juli-a-ko

# Closes # (if applicable).

## Changes proposed in this Pull Request

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2023-03-05 19:31 UTC, ekatef commented
@juli-a-ko amazing work! Thank you so much for the PR :)

2023-03-06 10:47 UTC, pz-max commented
Cool! Just some notes that need to be checked:

- Looks like some csv got deleted by accident
- All Python scripts should be GPL3 licensed (not MIT)
- rst files need to be checked if the license note is not conflicting the documentation (make html to create the documentation locally)

2023-03-06 11:13 UTC, ekatef commented
@pz-max thanks a lot for looking into it! We'll go point-by-point in the review round and then ask you for the second check. @juli-a-ko has done a very big work which currently needs to be carefully accommodated in the project

Max, there is also an additional question: it would be great to see the green reuse badge but it looks like we need to register the fork project on reuse. Not sure however if it wouldn't it be misuse of reuse infrastructure 🙂 What do you think?

2023-03-06 11:45 UTC, pz-max commented
> Max, there is also an additional question: it would be great to see the green reuse badge but it looks like we need to register the fork project on reuse. Not sure however if it wouldn't it be misuse of reuse infrastructure slightly_smiling_face What do you think?

Sure, go ahead with registering the badge on the fork to test it... we can delete the for registration afterwards? If not, let's do the badge stuff afterwards on the main repo :)

2023-03-07 07:43 UTC, euronion commented
This PR closes #599 if finished, right? :) Good work so far!

A few comments from my side as well:

* The `<year>` [does not need to be specified in the SPDX identifier](https://reuse.software/faq/#years-copyright), i.e. `reuse annotate --year="" ...` . I choose this with other recent options because I think it looks nicer and doesn't cause the urge to update it every year ;-)
* Some SPDX identifiers look broken (e.g. missing `#`) at beginning of line, `reuse lint` should complain about those
* Make sure to avoid redundant licence information, e.g. for `.github/*` via `.reuse/dep5` but also a licence specified in the individual files under `.github/` via an SPDX identifier
* Special attention is probably needed for the files in `scripts` which are based/copied from PyPSA-EUR and then partially adapted. E.g. `scripts/_helpers.py` contains mixed efforts from PyPSA-EUR and PyPSA-Earth and needs the appropriate CopyRightText as well as licence. It is worth noting that PyPSA-EUR underwent a [licence change in 2021](https://pypsa-eur.readthedocs.io/en/latest/release_notes.html#pypsa-eur-0-4-0-22th-september-2021) to MIT licence, but I think the old code fragments are from before that?
* @pz-max : Is it decided to go with GPLv3?
* We don't have a contributor agreement yet, in the meantime it could be helpful to include a checkbox in the [Pull Request template](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/.github/pull_request_template.md) like we do in [technology data](https://github.com/PyPSA/technology-data/blob/master/.github/pull_request_template.md), e.g.
```
[ ] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
```

2023-03-07 08:00 UTC, pz-max commented
All comments/suggestions from @euronion are valid (as always). 
- Regarding mixed efforts. I think  we could mention "PyPSA-Earth and PyPSA-Eur authors" on all scripts to keep things simple
- Correct, GPLv3 is the current solution

2023-03-07 22:30 UTC, ekatef commented
@euronion, @pz-max huge thanks for the comments!

Jonannes, that is perfect to have your expert opinion. Indeed, I absolutely agree with Max that it's worth to mention in all the scripts both PyPSA-Eur and PyPSA-Earth teams. A good point about the licensing consent!

2023-03-26 18:54 UTC, ekatef requested changes
@juli-a-ko, thanks a lot for the PR and sorry for taking a while to review it.

Have added few technical comments. Regarding checking rst files (source [reStructured Text](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) files used to build project documentation), will be happy to help in testing it :)

2023-03-26 18:54 UTC, ekatef commented on .github/pull_request_template.md
> + SPDX-License-Identifier: CC0-1.0
It looks like "#" is missed here

2023-03-26 18:54 UTC, ekatef commented on .gitignore
> +doc/configtables
Not sure we have to include csv-s and doc/configtables into gitignore

2023-03-26 18:54 UTC, ekatef commented on README.md
> +SPDX-FileCopyrightText: 2022-2023 PyPSA-Earth Authors
"#" seems to get lost

2023-03-26 18:54 UTC, ekatef commented on doc/configtables/atlite.csv
It looks like configtables were removed by accident :)

2023-03-26 19:04 UTC, pz-max commented
Hey everyone, I am currently working a PR for this and took some inspiration from here. I will push a PR this night.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Ekaterina ***@***.***>
Sent: Sunday, March 26, 2023 7:55:09 PM
To: pypsa-meets-earth/pypsa-earth ***@***.***>
Cc: Maximilian Parzen ***@***.***>; Mention ***@***.***>
Subject: Re: [pypsa-meets-earth/pypsa-earth] REUSE compliance badge_v.0 (PR #617)

This email was sent to you by someone outside the University.
You should only click on links or attachments if you are certain that the email is genuine and the content is safe.

@ekatef requested changes on this pull request.

@juli-a-ko<https://github.com/juli-a-ko>, thanks a lot for the PR and sorry for taking a while to review it.

Have added few technical comments. Regarding checking rst files (source reStructured Text<https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html> files used to build project documentation), will be happy to help in testing it :)

________________________________

In .github/pull_request_template.md<https://github.com/pypsa-meets-earth/pypsa-earth/pull/617#discussion_r1148616039>:

> @@ -1,3 +1,7 @@
+# SPDX-FileCopyrightText: 2022-2023 PyPSA-Earth Authors
+#
+ SPDX-License-Identifier: CC0-1.0


It looks like "#" is missed here

________________________________

In .gitignore<https://github.com/pypsa-meets-earth/pypsa-earth/pull/617#discussion_r1148616206>:

> @@ -31,6 +33,7 @@ resources/
 scripts/temp
 scripts/test.py
 test/tmp/
+doc/configtables


Not sure we have to include csv-s and doc/configtables into gitignore

________________________________

In README.md<https://github.com/pypsa-meets-earth/pypsa-earth/pull/617#discussion_r1148616397>:

> @@ -1,5 +1,7 @@
 # PyPSA-Earth
-
+#
+SPDX-FileCopyrightText: 2022-2023 PyPSA-Earth Authors


"#" seems to get lost

________________________________

On doc/configtables/atlite.csv<https://github.com/pypsa-meets-earth/pypsa-earth/pull/617#discussion_r1148616914>:

It looks like configtables were removed by accident :)

—
Reply to this email directly, view it on GitHub<https://github.com/pypsa-meets-earth/pypsa-earth/pull/617#pullrequestreview-1358084935>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOYZENJFCYJ7UDWJJXW4P7LW6CGI3ANCNFSM6AAAAAAVQKLVVY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336. Is e buidheann carthannais a th’ ann an Oilthigh Dhùn Èideann, clàraichte an Alba, àireamh clàraidh SC005336.

2023-03-26 19:16 UTC, ekatef commented
Hey @pz-max, thanks for notifying! Looking forward for your PR :)

2023-03-26 23:24 UTC, pz-max commented
@juli-a-ko @ekatef thanks for great try with the REUSE stuff. 
I just opened a PR at #651 which might interest you.
Sorry for rushing that, I just had some time today and ws curious :)

2023-04-02 09:15 UTC, closed without merging