Add-exception-to-build_pp
pz-max/pypsa-africa pull request #690
Opened 2023-04-18 14:19 UTC by Tomkourou

# Closes #678.

## Changes proposed in this Pull Request

Hopefully this is the final one!

## Checklist

- [x] I consent to the release of this PR's code under the GPLv3 license and non-code contributions under CC0-1.0 and CC-BY-4.0.
- [ ] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to `envs/environment.yaml` and `envs/environment.docs.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

2023-04-18 16:50 UTC, davide-f requested changes

2023-04-18 16:50 UTC, davide-f commented on scripts/build_powerplants.py
> +        )
Thank @Tomkourou!

I think we could encapsulate this into a function, like `def test_java_availability():` and place these lines as a content.

Then the call `test_java_availability()` can be placed  right at the beginning of main at around line 270.

I think we are close to finalize :)

2023-04-19 08:10 UTC, Tomkourou commented
@davide-f do you want the function to be placed in `_helpers.py` ?

2023-04-19 08:16 UTC, davide-f commented
> @davide-f do you want the function to be placed in `_helpers.py` ?

No need as it is a specific problem by powerplantmatching.
You may comment also about adding this feature there as well; they may be happy about it.

2023-04-19 08:19 UTC, davide-f commented
Actually, someone noticed the same and proposed a similar fix
https://github.com/PyPSA/powerplantmatching/pull/109/files

Let's see wait the berlin team things, if it is merged into powerplantmatching, maybe it becomes redundant here

2023-04-20 17:27 UTC, davide-f commented
I've just checked the PR into ppl and it seems that a similar fix will be available in ppl and it may be redundant here.
It may be worth if you could contribute directly there maybe proposing your approach, maybe first adding to the discussion (make a PR if they suggest them to do so).
What do you think?

2023-05-06 18:16 UTC, pz-max commented
Closing as appears to be already solved in ppm https://github.com/PyPSA/powerplantmatching/pull/109/files

2023-05-06 18:16 UTC, closed without merging